name: pr-build

on:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/base

jobs:
  build:
    name: Build base images for all platforms

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3.3.0
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Extract base image name
        id: custom-meta
        run: |
          echo "base-image-name=${DOCKER_TAG%%:*}" | tee -a $GITHUB_OUTPUT
        env:
          DOCKER_TAG: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}

      - name: Build base images
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc # v6.11.0
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: ${{ steps.custom-meta.outputs.base-image-name }}:buildcache
